services:
  db:
    image: mysql:8.0
    container_name: school3-db-prod
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=studentdevdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-prod:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: school3-backend-prod
    image: leventoner/school3-backend:latest
    restart: on-failure
    ports:
      - "8084:8083"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/studentdevdb

  frontend:
    container_name: school3-frontend-prod
    image: leventoner/school3-frontend:latest
    restart: on-failure
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  mysql-data-prod:
